apiVersion: v1
items:
- apiVersion: kiali.io/v1alpha1
  kind: Kiali
  metadata:
    annotations:
      ansible.sdk.operatorframework.io/verbosity: "1"
      meta.helm.sh/release-name: kiali-operator
      meta.helm.sh/release-namespace: kiali-operator
    finalizers:
    - kiali.io/finalizer
    generation: 1
    labels:
      app: kiali-operator
      app.kubernetes.io/instance: kiali-operator
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kiali-operator
      app.kubernetes.io/part-of: kiali-operator
      app.kubernetes.io/version: v1.72.0
      helm.sh/chart: kiali-operator-1.72.0
      version: v1.72.0
    name: kiali
    namespace: istio-system
    resourceVersion: "954808"
    uid: df03e0bb-c99c-4547-8af7-9e621f4bef36
  spec:
    deployment:
      accessible_namespaces:
      - '**'
    external_services:
      prometheus:
        url: http://kube-prometheus-stack-prometheus.observability:9090 #Update correct prometheus URL here
      grafana:
      dashboards:
      - name: "Istio Service Dashboard"
        variables:
          namespace: "var-namespace"
          service: "var-service"
      # - name: "Istio Workload Dashboard"
      #   variables:
      #     namespace: "var-namespace"
      #     workload: "var-workload"
      # - name: "Istio Mesh Dashboard"
      # - name: "Istio Control Plane Dashboard"
      # - name: "Istio Performance Dashboard"
      # - name: "Istio Wasm Extension Dashboard"
      enabled: true
      is_core: false
      url: http://kube-prometheus-stack-grafana.observability:80
      
  status:
    conditions:
    - ansibleResult:
        changed: 11
        completion: 2023-08-27T20:40:23.223918
        failures: 0
        ok: 73
        skipped: 56
      lastTransitionTime: "2023-08-27T20:39:27Z"
      message: Awaiting next reconciliation
      reason: Successful
      status: "True"
      type: Running
    - lastTransitionTime: "2023-08-27T20:40:23Z"
      message: Last reconciliation succeeded
      reason: Successful
      status: "True"
      type: Successful
    - lastTransitionTime: "2023-08-27T20:40:23Z"
      message: ""
      reason: ""
      status: "False"
      type: Failure
    deployment:
      accessibleNamespaces: '**'
      instanceName: kiali
      namespace: istio-system
    environment:
      isKubernetes: true
      kubernetesVersion: 1.27.4-eks-2d98532
      operatorVersion: v1.72.0
    progress:
      duration: "0:00:45"
      message: 6. Finished all resource creation
    specVersion: default
kind: List
metadata:
  resourceVersion: ""
